# Generated by Django 4.2.4 on 2023-09-05 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0003_adverts_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adverts',
            name='photo',
            field=models.ImageField(upload_to='my_adverts', verbose_name='Изображение'),
        ),
    ]
